### ISSUE TITLE
[Feature Request] Use .Xresources colors inside rainbow

### ISSUE THREAD

**Issue by Anachron** [wmutils/contrib#36]
This way no matter what theme I chose the window border colors will be matching. 
If there are none, use a fallback.

**Comment by z3bra** [comment]
No we won't add it, for multiple reasons:
1. We don't strive for feature completeness here, but simplicity.
2. The scripts in this repo should not rely on external tools.
3. We expect the users to do their own modifications to suit their setup.
4. Using Xresources makes the script way too specific.
5. It's called "rainbow.sh", not "xrdb-border.sh"
6. Using Xresources for that looks ugly as hell:
   ![ugly.gif](https://cloud.githubusercontent.com/assets/9267994/17165928/25ab8fb2-53d4-11e6-98c1-f9531e1247ae.gif)

Again, this repo should be a place to demonstrate the capabilities of wmutils by
performing actions that are not possible with traditionnal window managers.
I do agree that some scripts don't fullfill this goal, but all the scripts in
this repo are stripped to the bare minimum, so they can serve as a "sane base"
to build on.

Anachron wrote:

> This way no matter what theme I chose the window border colors will be matching. 
> If there are none, use a fallback.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/wmutils/contrib/issues/36

## 

If you want to stay dad you've got to polish your image. I think the image
we need to create for you is "repentant but learning".  
    -- Calvin

**Comment by Anachron** [comment]
Alright thanks for the clarification, I will just modify it for myself then. :)
