### ISSUE TITLE
Mapw issues

### ISSUE THREAD

**Issue by derrickcope** [wmutils/contrib#45]
Mapw no longer works, or works sometimes after the new xorg update on Arch Linux. Is anyone else experiencing similar issues? Also, focus.sh isn't working correctly. I have to click twice to focus on a window. Not sure if it is a problem with focus.sh or underneath.sh

**Comment by z3bra** [comment]
> Mapw no longer works, or works sometimes after the new xorg update on
> Arch Linux. Is anyone else experiencing similar issues?

Hello,

What version of xorg are you running? Did the libxcb version changed
as well?

"no longer works" and "works sometimes" are two different things. Could
you please elaborate on this?
First of all, do your tests without any window manager running. For
example, use a .xinitrc with ONLY the following line:

	exec xterm

This way we make sure no other software is running. Then, in the xterm
window, run the following command:

	mapw -u `lsw`; sleep 3; mapw -m `lsw -u`

It should hide your xterm window, wait 3 seconds and bring it back. If
the command works on first try, you can try to run it multiple times to
see if it fails "randomly"

> Also, forces.sh isn't working correctly. I have to click twice to
> forces on a window. Not sure if it is a problem with focus.sh or
> underneath.sh

I have no idea what this `force.sh` script is. If you would like to
troubleshoot it, you probably should try both `focus.sh` and
`underneath.sh` separately with the same setup as for `mapw`.
If the tools work as expected with only an xterm window, it would mean
the tools are working correctly.
The issue will most likely be related to your environment, or tool.

**Comment by derrickcope** [comment]
I am trying to narrow down what is causing the issue. lbinput and xorg were updated. xorg is 1.19.1-1.
sxhkd seems to be having issues as well so I cant tell what is what. force.sh should be focus.sh. 
I am going to try xbindkeys rather than sxhkd to see what problems that solves first if any.

**Comment by ghost** [comment]
Hey there,

I use Arch Linux too and have the same problem after the update.

Can't tell if sxhkd is also broken (because of some libraries, I use downgraded sxhkd 0.5.5), but it certainly lags when I move a window, for example.

Nevertheless, all focus-oriented utilities are somehow broken, so my guess is mapw. When I test it in command line, it can work 3 times in a row or it can do nothing 5 times in a row, you never know.

By the way, I tested it in a bare X environment and the behavior is analogical.

**Comment by derrickcope** [comment]
I tried xbindkeys keys and the problem was still there as well. I think there is some issue with the new default input driver libinput. Something is amiss with how input is gotten from the keyboard and mouse. The problem is it works sometimes and doesn't work other times so it is hard to determine what is and isn't working. I tried openbox today and their keybinds are working fine.

**Comment by z3bra** [comment]
This issue is related to the core utilities. Another issue has been openned so I'm closing this one. Please now refer to https://github.com/wmutils/core/issues/53
